<?php

use Chayka\Comments\OptionHelper;
/**
 * @var \Chayka\MVC\View $this
 */
$this->declareVars([
	'order' => OptionHelper::getOption('comment_order', 'asc'),
	'preload' => OptionHelper::getOption('preload_comments', true),
	'perPage' => OptionHelper::getOption('comments_per_page', 50),
	'requireNameEmail' => OptionHelper::getOption('require_name_email', true),
	'requireAuth' => OptionHelper::getOption('comment_registration', false),
	'avatarSize' =>OptionHelper::getOption('avatar_size', 48),
]);

if(post_type_supports( get_post_type(), 'comments' )):
$direct = $this->order == 'asc';
$commentsAreClosed = ! comments_open();
$thePost = \Chayka\WP\Models\PostModel::unpackDbRecord(get_post());
?>
<script>
	var Chayka = window.Chayka || {};
	Chayka.Posts = Chayka.Posts || {};
	Chayka.Posts.postsById = Chayka.Posts.postsById || {};
	Chayka.Posts.postsById[<?php the_ID();?>] = <?php echo \Chayka\WP\Helpers\JsonHelper::encode($thePost);?>;
</script>
<?php
if($this->preload):
	$query = \Chayka\WP\Queries\CommentQuery::query(get_the_ID())
		->number($this->perPage)
		->status(\Chayka\WP\Helpers\AclHelper::isAdmin()?'all':'approve')
		->orderBy('comment_ID')
		->order('DESC'); // yeah, that's correct and then reverse it
	$userId = get_current_user_id();
	if($userId){
		$query->includeUnapproved(array($userId));
	}
	$comments = $query->select();
	if($this->order == 'asc'){
		$comments = array_reverse($comments);
	}
	$total = $query->selectCount();
?>
<script>
	Chayka.Comments = Chayka.Comments || {};
	Chayka.Comments.commentsByPostId = Chayka.Comments.commentsByPostId || {};
	Chayka.Comments.commentsByPostId[<?php the_ID();?>] = {
		comments: <?php echo \Chayka\WP\Helpers\JsonHelper::encode($comments);?>,
		total: <?php echo (int)$total;?>
	};
</script>
<?php endif;
	$showMorePaneHtml = '<div class="show_hidden_pane chayka-comments-width" data-ng-hide="total <= comments.length"><span class="link chayka-comments-link" data-ng-click="showMore(perPage)">{{"Show older comments..."|nls}}</span><span class="shown_total">{{comments.length}} {{"of"|nls}} {{total}} {{"shown" | nls}}</span></div>';
	$editorHtml = $commentsAreClosed?
		'<div class="no_comments chayka-comments-width" data-ng-show="!!comments.length">'. $this->_( 'Comments are closed') . '</div>':
		'<div data-comment-editor="editors.static" data-post-id="postId" data-require-name-email="requireNameEmail" data-require-auth="requireAuth"></div>';

?>
<div class="chayka-comments" ><a name="comments"></a>
	<?php if ( post_password_required() ) : ?>
	<div class="no_password chayka-comments-width"><?php $this->__( 'This post is password protected. Enter the password to view any comments.'); ?></div>
	<?php else: \Chayka\WP\Helpers\AngularHelper::enqueueScriptStyle('chayka-comments');?>
		<div class="comments_controller chayka-comments-width" data-ng-controller="comments" data-post-id="<?php the_ID();?>" data-order="<?php echo $this->order;?>" data-read-only="<?php echo $commentsAreClosed?>" data-import="<?php echo $this->preload?'Chayka.Comments.commentsByPostId.'.get_the_ID():'';?>" data-per-page="<?php $this->escape($this->perPage);?>" data-require-name-email="<?php echo $this->requireNameEmail?>" data-require-auth="<?php echo $this->requireAuth;?>" data-avatar-size="<?php echo $this->avatarSize;?>" data-ng-class="{order_asc: order === 'ASC', order_desc: 'DESC', require_name_email: !!requireNameEmail, read_only: !!readOnly}" data-ng-cloak>
			<?php echo $direct?$showMorePaneHtml:$editorHtml;?>
			<div class="comments-list" data-ng-show="!!comments.length">
				<div data-ng-repeat="comment in comments track by comment.id" data-comment-item="comment"></div>
			</div>
			<?php echo !$direct?$showMorePaneHtml:$editorHtml;?>
			<div data-modal="editorPopup">
				<div data-comment-editor="editors.dynamic" data-post-id="postId" data-require-name-email="requireNameEmail"></div>
			</div>
			<div data-modal="dialogPopup">
				<div class="chayka-comments-dialog" data-ng-class="{mode_reply: dialog.mode === 'reply', mode_replies: dialog.mode === 'replies'}">
					<h3>{{'Comment'|nls}}:</h3>
					<div data-comment-item="dialog.parentComment"></div>
					<h3>{{(dialog.replies.length > 1?'Replies':'Reply')|nls}}:</h3>
					<div class="replies_list">
						<div data-ng-repeat="comment in dialog.replies | orderBy : 'id' track by comment.id" data-comment-item="comment"></div>
					</div>
				</div>
			</div>
		</div>
	<?php endif;?>
</div>
<?php endif;